; Generated by Auto-GUI 3.0.1
Application := "BeamNG.drive "
Gui Font, s9, Segoe UI
Gui Add, Button, x280 y58 w80 h23 , Exit
Gui Add, Button, x24 y58 w80 h23 gInstall, ReInstall
Gui Add, Button, x136 y58 w112 h23 gFSN, Go Fullscreen
Gui Add, Text, x16 y8 w357 h50, This will boot with BeamNG. Click Go Fullscreen `nor "R CTRL" to return to Beamng fullscreen at anytime and place.  
Gui Show, w384 h110, BMNG Fullscreen Fix
WinSet, AlwaysOnTop,, BMNG Fullscreen Fix,
Return


;FileSelectFolder, OutputVar, , 3
;if OutputVar =
;    MsgBox, You didn't select a folder.
;else
;    MsgBox, You selected folder "%OutputVar%".


Install:
{	
	MsgBox 0x1, Are you sure you'd like to reinstall?, Reinstall can help with updates`, or if you have moved files. 

IfMsgBox If MsgBox Cancel, 
{
return
}
else 
{
	SetWorkingDir %A_ScriptDir%
	gameusualdir := "C:\Program Files (x86)\Steam\steamapps\common\BeamNG.drive\BeamNG.drive.exe"
	MsgBox, Please locate the game exe for Beamng.Drive 
	FileSelectFile, FullGameDirectory, , %gameusualdir%, Select a game, application (*.exe)
	if (FullGameDirectory = "")
		MsgBox, I haven't received a file value.
;        else
;        {
;            SplitPath, FullGameDirectory, Gamewithextension, gamefolder, Gameextenstion, Gamenameonly,
;        }
	Firsthalf := "\BeamNG.drive\0.24\settings\logfile.txt"
	loglocal := LocalAppData Firsthalf
  ; write game location to local app data and settings 
	MsgBox, %loglocal%
	MsgBox, %FullGameDirectory%
	FileDelete, %loglocal%
	FileAppend, %FullGameDirectory%, %loglocal%
	run, setup.bat
}
}
return

Exit:
{
    ExitApp
}
return





FSN:
{
   ControlFocus,, %Application%
    Sleep, 500
    ControlSend,, {RAlt Down}{Enter}{RAlt Up}, %Application%
}
return

~RCtrl::
ControlFocus,, %Application%
Sleep, 500
ControlSend,, {Alt Down}{Enter}{Alt Up}, %Application%
return

Pause::ExitApp

 